
# try this instead of cp hard link
# mount squashfs  for reading and writing  temporally in RAM 
#  mount  mysquash.fs folder1
#  mount -t tmpfs -o size=128M tmpfs folder2
#  mount -t aufs  -o dirs=folder2=rw:folder1=ro  folder1  folder3
#  cd folder3/
#  umount folder3
#  umount folder2
#  umount folder1



#  http://localhost:8080/web4/User/Login.action
#  http://localhost:8080/web4/User/Welcome                                                     

#  http://localhost:8080/web4/html/index.html
#  http://localhost:8080/web4/html/FirstJsp.jsp
#  http://localhost:8080/web4/html/index.html
#  http://localhost:8080/web4/html/addLeague.do?
#  http://localhost:8080/web4/html/testSession.view
#  http://localhost:8080/web4/html/myCookie.view


# hard link -l by cp ;;  -r recursive copy ;; -f (force copy and delete the exist file) ;; -l hard link
# 0 ok ;; 1 fail => c-h e(view message errors)
# * means copy subdirectories and files but not this directory etc
(shell-command "cp -f -r -l  /home/jdee_workspace/web4/src/resources/WEB-INF/*        /home/jdee_workspace/sourcePathx/servers/tomcat9/webapps/web4/WEB-INF/ ")
(shell-command "cp -f -r -l  /home/jdee_workspace/web4/src/resources/web/html/*       /home/jdee_workspace/sourcePathx/servers/tomcat9/webapps/web4/html/    ")


#
GET http://localhost:8080/employees
#




#C-c C-c send
:myName   =Ahmed
:myPass   =hi
GET http://localhost:8080/hello?name=:myName&pass=:myPass
#                             


#C-c C-c send
:myName   =ali
:myPass   =hi2
GET http://localhost:8080/welcome?name=:myName&pass=:myPass
#                             



#C-c C-c send
:myName   =ali
:myPass   =hi2
GET http://localhost:8080/employees
#                             




#C-c C-c send
:myName   =Ahmed
:myPass   =hi
GET http://localhost:8080/web4/User/Login.action?username=:myName&password=:myPass
#                             

# succeeded league
# c-c c-c send query request,
# c-c c-n/p previous next query
:myYear   =2007
:myTitle  =ok
:mySeason =Spring
GET http://localhost:8080/web4/html/addLeague.do?year=:myYear&title=:myTitle&season=:mySeason
# succeeded league

# list all  leagues
GET http://localhost:8080/web4/html/listLeagues.view
# list all  leagues

# [year must be a number]
:myYear   =what
:myTitle  =ok
:mySeason =Spring
GET http://localhost:8080/web4/html/addLeague.do?year=:myYear&title=:myTitle&season=:mySeason
# [year must be a number]

# [please enter year between 2005-2010]
:myYear   =20
:myTitle  =ok
:mySeason =Spring
GET http://localhost:8080/web4/html/addLeague.do?year=:myYear&title=:myTitle&season=:mySeason
# [please enter year between 2005-2010]

#[please enter title]
:myYear   =2008
:mySeason =Winter
GET http://localhost:8080/web4/html/addLeague.do?year=:myYear&title=&season=:mySeason
#[please enter title]

# [please enter season]
:myYear   =2007
:myTitle  =hi
:mySeason =Unknown
GET http://localhost:8080/web4/html/addLeague.do?year=:myYear&title=:myTitle&season=:mySeason
# [please enter season]

# [year must be a number]
# [please enter title]
# [please enter season]
:mySeason =Unknown
GET http://localhost:8080/web4/html/addLeague.do?year=&title=&season=:mySeason
# [year must be a number]
# [please enter title]
# [please enter season]

:first_name   =anas2
:last_name    =moh
:address      =syria
:salary       =333
GET http://localhost:8080/employeeSave?firstName=:first_name&lastName=:last_name&address=:address&salary=:salary


#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
"firstName": "hamed2",
"lastName": "ali",
"address": "jordan",
"salary": 4400.0
}

#


#

PUT http://localhost:8080/employeeSaveByPut
Content-Type: application/json
{
"id": 47,
"firstName": "hamedAli",
"lastName": "ali",
"address": "jordan",
"salary": 4400.0
}

#

PUT http://localhost:8080/employeeSaveByPut
Content-Type: application/json
{
"id": 47,
"firstName": "hamedDiaa",
"lastName": "ali",
"address": "jordan",
"salary": 4400.0
}

#


# comment

POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
{
"firstName": "hamed2",
"lastName": "ali",
"address": "jordan",
"salary": 4400.0
}





# [old ] 
#  because ln cant link directory
# hard link for jsp files
# -P hard link, -f replace existing files (return 0 true) (return 1 fail)
# hard link not allowed for directory
# (shell-command "ln -f -P  /home/jdee_workspace/web4/web/html/*.*  /home/jdee_workspace/sourcePathx/servers/tomcat7/webapps/web4/html/       ")
# (shell-command "ln -f -P  /home/jdee_workspace/web4/etc/*.*       /home/jdee_workspace/sourcePathx/servers/tomcat7/webapps/web4/WEB-INF/    ")



# use only M-x jdee-ant-build => jdee-ant.el or c-c c-v c-b
# or from commandl-line, type ant
# ignore tomcat-Copy-My-Project-Files-to-Tomcat
(defun tomcat-Copy-My-Project-Files-to-Tomcat()
 (interactive)
 (copy-directory  "/home/jdee_workspace/web4/html"      "/home/jdee_workspace/sourcePathx/servers/tomcat9/webapps/web4/")
 (copy-directory  "/home/jdee_workspace/web4/etc/data"  "/home/jdee_workspace/sourcePathx/servers/tomcat9/webapps/web4/WEB-INF/")
 (copy-file "/home/jdee_workspace/web4/web.xml"         "/home/jdee_workspace/sourcePathx/servers/tomcat9/webapps/web4/WEB-INF/"  1)
)

# 
# M-x tomcat-start
# M-x tomcat-stop
# M-x tomcat-clean
#

# context.log apache server
# /home/jdee_workspace/sourcePathx/servers/tomcat7/logs/


# old server old server old server
# (defun cp-My-Project-Files-Copy-to-Tomcat()
#  (interactive)
#  (copy-directory  "/home/jdee_workspace/web4/html"    "/var/lib/tomcat7/webapps/web4/")
#  (copy-directory  "/home/jdee_workspace/web4/etc/data"    "/var/lib/tomcat7/webapps/web4/WEB-INF/")
#  (copy-file "/home/jdee_workspace/web4/web.xml"           "/var/lib/tomcat7/webapps/web4/WEB-INF/"  1)
# )
# clear apache, remove project from apache
# (delete-directory "/var/lib/tomcat7/webapps/web4/" 1)

#  M-x  cp-My-Project-Files-Copy-to-Tomcat
#  (cp-My-Project-Files-Copy-to-Tomcat)

# context.log apache server
# /var/lib/tomcat7/logs/


#  (copy-directory  "html"    "/var/lib/tomcat7/webapps/web4/")
#  (copy-file "web.xml"       "/var/lib/tomcat7/webapps/web4/WEB-INF/"  1)

#  (copy-file "html/index.html"    "/var/lib/tomcat7/webapps/web4/"       1)
#  (copy-file "html/listAll.html"  "/var/lib/tomcat7/webapps/web4/"       1)
#  (copy-file "html/addLeague.html"  "/var/lib/tomcat7/webapps/web4/"     1)
# 
#  http://localhost:8080/web4/html/index.html

#  debug 8000
#  http://localhost:8000/web4/html/index.html

#  http://localhost:8080/web4/index.html
#  http://localhost:8080/web4/hi
#  http://localhost:8080/web4/listAll.html
#  http://localhost:8080/web4/league
#  http://localhost:8080/web4/html/index.html
#  http://localhost:8080/web4/html/addLeague.html
#  http://localhost:8080/web4/html/add_league.do?year=2009&title=hi&season=winter

#  http://127.0.0.1:8080/web4/html/index.html
#  http://127.0.0.1:8080/web4/html/index.html
#  http://127.0.0.1
# 
#
GET http://localhost:8080/web4/index.html
#GET http://127.0.0.1:4444/web4/index.html
#

# error in year
GET http://localhost:8080/web4/html/addLeague.do?year=2222&title=hi&season=winter
#

# good league
GET http://localhost:8080/web4/html/addLeague.do?year=2008&title=hi2&season=winter
#



GET http://localhost:8080/web4/hi
#GET http://127.0.0.1:4444/web4/hi
#
GET http://localhost:8080/web4/index.html
#
# c-c c-c send query request,
# c-c c-n/p previous next query 
# GET http://127.0.0.1:8080/web4/add_league.do?year=2005&title=hi&season=spring
:year   =200
:season =spring
:title  =ok

GET http://localhost:8080/web4/html/add_league.do?year=:year&title=:title&season=:season

User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

# end
# end

# c-c c-c send query request
# GET http://127.0.0.1:8080/web4/add_league.do?year=2005&title=hi&season=spring
:query1 = 55
:query2 = omar
:query3 = winter

GET http://127.0.0.1:8080/web4/add_league.do?year=:query1&title=:query2&season=:query3
User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

# end
#

# c-c c-c send query request
# GET http://127.0.0.1:8080/web4/add_league.do?year=2005&title=hi&season=spring
:query1 = -55
:query2 = omar
:query3 = winter

GET http://127.0.0.1:8080/web4/add_league.do?year=:query1&title=:query2&season=:query3
User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

# end
#

# c-c c-c send query request
# GET http://127.0.0.1:8080/web4/add_league.do?year=2005&title=hi&season=spring
:query1 = 2010
:query2 = omar
:query3 = winter

GET http://127.0.0.1:8080/web4/add_league.do?year=:query1&title=:query2&season=:query3
User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

# end
#

# c-c c-c send query request
# GET http://127.0.0.1:8080/web4/add_league.do?year=2005&title=hi&season=spring
:query1 = 2010
:query2 = omar
:query3 = winter

GET http://127.0.0.1:8080/web4/add_league.do?year=:query1&title=:query2&season=:query3
User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

# end
#





# proxy  4444
:query1 = 2010
:query2 = ali
:query3 = winter

GET http://127.0.0.1:4444/web4/add_league.do?year=:query1&title=:query2&season=:query3
User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded
#
# end





#
 GET http://127.0.0.1:8080/web4/add_league.do?year=2005&title=hi&season=spring
  after context 05
#







# Returns POST data.
POST http://bin.org/post
Content-Type: application/json
{
    "jql": "project = HSP",
    "startAt": 0,
    "maxResults": 15,
    "fields": [
        "summary",
        "status",
        "assignee"
    ]
}

# hi
GET http://192.168.1.1



# Returns POST data.
# POST http://192.168.1.1/boaform/admin/formLogin
POST http://192.168.1.1/boaform/admin/formWirelessTbl
User-Agent:  Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:54.0) Gecko/20100101 Firefox/54.0
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Host: 192.168.1.1
Content-Type: application/x-www-form-urlencoded
{
 "username": "user" 
 "password": "useruseruser"
 "submit-url": "admin login.asp"
}




##
POST http://192.168.1.1/boaform/admin/formLogin/
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 3.2; Trident/22.0; IEMobile/9.0)
Accept: text/html, text/*;q=0.5, image/*, application/*, video/*, audio/*, x-content/*, inode/*, x-scheme-handler/*, misc/*
Accept-Encoding: gzip, compress, bzip, bzip2, deflate
Accept-Language: en;q=1.0
Host: 192.168.1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 89
Referer: http://192.168.1.1/boaform/admin/formLogin/
{
 "username": "user" 
 "password": "useruseruser"
 "submit-url": "admin login.asp"
 "save": "Login"
 "challenge":
}
HTTP/1.0 301 Moved Permanently
Date: Wed, 24 Apr 2019 21:12:00 GMT
Server: Boa/0.93.15
Connection: close
Content-Type: text/html
Location: /


/boaform/admin/formWirelessTbl



================================================================



#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
"firstName": "hamed2",
"lastName": "ali",
"address": "jordan",
"salary": 4400.0
}
#

#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
"firstName": "ahmad", 
"lastName": "ali", 
"address": "jordan", 
"salary": 100
}
#

#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
"firstName": "moh", 
"lastName": "ali", 
"address": "jordan",
"salary": 200
}
#

#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
"firstName": "saad", 
"lastName": "ali", 
"address": "jordan", 
"salary": 33300
}
#


#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
"firstName": "khawla", 
"lastName": "omar", 
"address": "KSA", 
"salary": 400
}
#







#
POST http://localhost:8080/employeeDelByEmp
Content-Type: application/json
{
"id": 10,
"firstName": "moh",
"lastName": "ali",
"address": "jordan",
"salary": 200
}
#	



#
POST http://localhost:8080/employeeDelByEmp
Content-Type: application/json
{
"id": 16
}
#	



#
POST http://localhost:8080/employeeDelByEmp
Content-Type: application/json
{
"firstName": "khawla"
}
#	




#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
 "firstName":"ahmad",
 "lastName":"ali",
 "address":"jordan",
 "salary":100
}

#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
 "firstName":"moh",
 "lastName":"ali",
 "address":"jordan",
 "salary":200
}

#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
 "firstName":"saad",
 "lastName":"ali",
 "address":"jordan",
 "salary":333
}

#
POST http://localhost:8080/employeeSaveByPost
Content-Type: application/json
{
 "id": 23,
 "firstName":"khawlaa",
 "lastName":"omara",
 "address":"KSAa",
 "salary":400
}
#



#

GET http://localhost:8080/employees

#


#

GET http://localhost:8080/emp/api/employees

#


